import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { Inter as FontSans } from "next/font/google";
import { type Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";

import { cn } from "@/lib/utils";
import { Toaster } from "@/app/_components/ui/toaster";

export const metadata: Metadata = {
  title: "Trivia Game",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={
        cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable,
        ) + ` ${GeistSans.variable}`
      }
    >
      <body>
        <Toaster />
        <TRPCReactProvider>{children}</TRPCReactProvider>
      </body>
    </html>
  );
}
